name: my-tests
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: npm
      - run: make setup
      - run: make lint
      - run: make test
